build_from:
  amd64: ghcr.io/hassio-addons/base/amd64:20.1.0
  aarch64: ghcr.io/hassio-addons/base/aarch64:20.1.0
  armv7: ghcr.io/hassio-addons/base/armv7:20.1.0
labels:
  org.opencontainers.image.title: HAPilot
  org.opencontainers.image.description: Universal Telegram bot for Home Assistant
  org.opencontainers.image.source: https://github.com/grizlygreen/hapilot-addons
  org.opencontainers.image.licenses: MIT
